SistemKasir/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemKasir.Models;
using SistemKasir.Services;

namespace SistemKasir.Controllers
{
    public class KategoriController : Controller
    {
        private readonly sistem_kasirContext _context;

        public KategoriController(sistem_kasirContext context)
        {
            _context = context;
        }

        // GET: Kategori
        public async Task<IActionResult> Index()
        {
            return _context.Kategori != null ?
                        View(await _context.Kategori.OrderBy(d => d.Deskripsi).ToListAsync()) :
                        Problem("Entity set 'sistem_kasirContext.Kategori'  is null.");
        }

        // GET: Kategori/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kategori/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                var prefix = "KAT";
                var masterIdData = _context.MasterId.Where(d => d.PrefixId == prefix)?.FirstOrDefault();
                var idKategori = GenerateIdServices.GetID(prefix, masterIdData);

                if (idKategori != null)
                {
                    // Simpan Kategori
                    kategori.IdKategori = idKategori;
                    _context.Add(kategori);

                    // Update counter table Master ID
                    masterIdData.Counter = masterIdData.Counter + 1;
                    _context.MasterId.Update(masterIdData);

                    await _context.SaveChangesAsync();

                    TempData["success"] = "Kategori berhasil ditambahkan";
                }

                return RedirectToAction(nameof(Index));
            }
            return View(kategori);
        }

        // GET: Kategori/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Kategori == null)
            {
                return NotFound();
            }

            var kategori = await _context.Kategori.FindAsync(id);
            if (kategori == null)
            {
                return NotFound();
            }
            return View(kategori);
        }

        // POST: Kategori/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Kategori kategori)
        {
            if (id != kategori.IdKategori)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kategori);
                    await _context.SaveChangesAsync();

                    TempData["success"] = "Kategori berhasil di update";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KategoriExists(kategori.IdKategori))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kategori);
        }

        // POST: Kategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Kategori == null)
            {
                return Problem("Entity set 'sistem_kasirContext.Kategori'  is null.");
            }
            var kategori = await _context.Kategori.FindAsync(id);
            if (kategori != null)
            {
                _context.Kategori.Remove(kategori);
            }

            await _context.SaveChangesAsync();

            TempData["success"] = "Kategori berhasil dihapus";

            return RedirectToAction(nameof(Index));
        }

        private bool KategoriExists(string id)
        {
            return (_context.Kategori?.Any(e => e.IdKategori == id)).GetValueOrDefault();
        }
    }
}

SistemKasir/Controllers/ProdukController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemKasir.Models;
using SistemKasir.Services;
using SistemKasir.ViewModels;

namespace SistemKasir.Controllers
{
    public class ProdukController : Controller
    {
        private readonly sistem_kasirContext _context;

        public ProdukController(sistem_kasirContext context)
        {
            _context = context;
        }

        // GET: Produk
        public async Task<IActionResult> Index()
        {
            //var sistem_kasirContext = _context.Produk.Include(p => p.IdKategoriNavigation).OrderBy(d => d.DeskripsiProduk);
            //return View(await sistem_kasirContext.ToListAsync());

            var listDataProduk = await _context.Produk
                .Join(_context.Kategori, p => p.IdKategori, k => k.IdKategori, (p, k) => new
                {
                    idProduk = p.IdProduk,
                    kategori = k.Deskripsi,
                    namaProduk = p.NamaProduk,
                    deskripsiProduk = p.DeskripsiProduk,
                    harga = p.Harga,
                    stok = p.Stok,
                    status = p.Status,
                }).Select(d => new ProdukViewModel()
                {
                    IdProduk = d.idProduk,
                    Kategori = d.kategori,
                    NamaProduk = d.namaProduk,
                    DeskripsiProduk = d.deskripsiProduk,
                    Harga = d.harga,
                    Stok = d.stok,
                    Status = d.status
                }).ToListAsync();

            return View(listDataProduk);
        }

        // GET: Produk/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null || _context.Produk == null)
        //    {
        //        return NotFound();
        //    }

        //    var produk = await _context.Produk
        //        .Include(p => p.IdKategoriNavigation)
        //        .FirstOrDefaultAsync(m => m.IdProduk == id);
        //    if (produk == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(produk);
        //}

        // GET: Produk/Create
        public IActionResult Create()
        {
            ViewData["IdKategori"] = new SelectList(_context.Kategori, "IdKategori", "Deskripsi");
            return View();
        }

        // POST: Produk/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Produk produk)
        {
            //if (produk.NamaProduk == null)
            //{
            //    ModelState.AddModelError("NamaProduk", "Nama Produk harus diisi.");
            //}
            if (ModelState.IsValid)
            {
                var prefix = "PRD";
                var masterIdData = _context.MasterId.Where(d => d.PrefixId == prefix)?.FirstOrDefault();
                var idProduk = GenerateIdServices.GetID(prefix, masterIdData);

                if (idProduk != null)
                {
                    // Simpan Kategori
                    produk.IdProduk = idProduk;
                    produk.DibuatOleh = "Admin";    // nanti di edit jadi pakai user yg login
                    _context.Add(produk);

                    // Update counter table Master ID
                    masterIdData.Counter = masterIdData.Counter + 1;
                    _context.MasterId.Update(masterIdData);

                    await _context.SaveChangesAsync();

                    TempData["success"] = "Produk berhasil ditambahkan";
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKategori"] = new SelectList(_context.Kategori, "IdKategori", "Deskripsi", produk.IdKategori);
            return View(produk);
        }

        // GET: Produk/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Produk == null)
            {
                return NotFound();
            }

            var produk = await _context.Produk.FindAsync(id);
            if (produk == null)
            {
                return NotFound();
            }
            ViewData["IdKategori"] = new SelectList(_context.Kategori, "IdKategori", "Deskripsi", produk.IdKategori);
            return View(produk);
        }

        // POST: Produk/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Produk produk)
        {
            if (id != produk.IdProduk)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produk);
                    await _context.SaveChangesAsync();

                    TempData["success"] = "Produk berhasil di update";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdukExists(produk.IdProduk))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKategori"] = new SelectList(_context.Kategori, "IdKategori", "Deskripsi", produk.IdKategori);
            return View(produk);
        }

        // GET: Produk/Delete/5
        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null || _context.Produk == null)
        //    {
        //        return NotFound();
        //    }

        //    var produk = await _context.Produk
        //        .Include(p => p.IdKategoriNavigation)
        //        .FirstOrDefaultAsync(m => m.IdProduk == id);
        //    if (produk == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(produk);
        //}

        // POST: Produk/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Produk == null)
            {
                return Problem("Entity set 'sistem_kasirContext.Produk'  is null.");
            }
            var produk = await _context.Produk.FindAsync(id);
            if (produk != null)
            {
                _context.Produk.Remove(produk);
            }

            await _context.SaveChangesAsync();

            TempData["success"] = "Produk berhasil dihapus";

            return RedirectToAction(nameof(Index));
        }

        private bool ProdukExists(string id)
        {
            return (_context.Produk?.Any(e => e.IdProduk == id)).GetValueOrDefault();
        }
    }
}

SistemKasir/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemKasir.Models;
using SistemKasir.Services;
using BC = BCrypt.Net.BCrypt;

namespace SistemKasir.Controllers
{
    public class UserController : Controller
    {
        private readonly sistem_kasirContext _context;

        public UserController(sistem_kasirContext context)
        {
            _context = context;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
              return _context.User != null ? 
                          View(await _context.User.ToListAsync()) :
                          Problem("Entity set 'sistem_kasirContext.User'  is null.");
        }

        // GET: User/Details/5
        //public async Task<IActionResult> Details(string id)
        //{
        //    if (id == null || _context.User == null)
        //    {
        //        return NotFound();
        //    }

        //    var user = await _context.User
        //        .FirstOrDefaultAsync(m => m.IdUser == id);
        //    if (user == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(user);
        //}

        // GET: User/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                var prefix = "USR";
                var masterIdData = _context.MasterId.Where(d => d.PrefixId == prefix)?.FirstOrDefault();
                var idUser = GenerateIdServices.GetID(prefix, masterIdData);

                if (idUser != null)
                {
                    // hash password
                    var passwordHash = BC.HashPassword(user.Password);

                    // Simpan User
                    user.IdUser = idUser;
                    user.Password = passwordHash;
                    user.DibuatOleh = "Admin";  // nanti diubah pakai yg login
                    _context.Add(user);

                    // Update counter table Master ID
                    masterIdData.Counter = masterIdData.Counter + 1;
                    _context.MasterId.Update(masterIdData);

                    await _context.SaveChangesAsync();

                    TempData["success"] = "User berhasil ditambahkan";
                }

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, User user)
        {
            if (id != user.IdUser)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();

                    TempData["success"] = "User berhasil di update";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.IdUser))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Delete/5
        //public async Task<IActionResult> Delete(string id)
        //{
        //    if (id == null || _context.User == null)
        //    {
        //        return NotFound();
        //    }

        //    var user = await _context.User
        //        .FirstOrDefaultAsync(m => m.IdUser == id);
        //    if (user == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(user);
        //}

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.User == null)
            {
                return Problem("Entity set 'sistem_kasirContext.User'  is null.");
            }
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }
            
            await _context.SaveChangesAsync();

            TempData["success"] = "User berhasil dihapus";

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
          return (_context.User?.Any(e => e.IdUser == id)).GetValueOrDefault();
        }
    }
}

SistemKasir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-theme="pastel">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemKasir</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/SistemKasir.styles.css" asp-append-version="true" />*@
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" type="text/css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />

    @*Fonts Google*@
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container-custom">
        <div class="sidebar">
            <div class="header">
                <div class="list-item">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        @*<img src="~/icon/Youtube.svg" alt="" class="icon" />*@
                        <span class="description-header">Sistem Kasir</span>
                    </a>
                </div>
                <div class="illustration">
                    <img src="~/icon/Illustration.png" alt="" />
                </div>
            </div>
            <div class="main">
                <div class="list-item">
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/icon/Dashboard.svg" alt="" class="icon" />
                        <span class="description">Dashboard</span>
                    </a>
                </div>
                <div class="list-item">
                    <a asp-area="" asp-controller="Kategori" asp-action="Index">
                        <img src="~/icon/Category.svg" alt="" class="icon" />
                        <span class="description">Kategori</span>
                    </a>
                </div>
                <div class="list-item">
                    <a asp-area="" asp-controller="Produk" asp-action="Index">
                        <img src="~/icon/Event.svg" alt="" class="icon" />
                        <span class="description">Produk</span>
                    </a>
                </div>
                <div class="list-item">
                    <a asp-area="" asp-controller="User" asp-action="Index">
                        <img src="~/icon/Team.svg" alt="" class="icon" />
                        <span class="description">User</span>
                    </a>
                </div>
                <div class="list-item">
                    <a asp-area="" asp-controller="Transaksi" asp-action="Index">
                        <img src="~/icon/Explore.svg" alt="" class="icon" />
                        <span class="description">Transaksi</span>
                    </a>
                </div>
                <div class="list-item">
                    <a href="#">
                        <img src="~/icon/Analytics.svg" alt="" class="icon" />
                        <span class="description">Report</span>
                    </a>
                </div>
                <div class="list-item">
                    <a href="#">
                        <img src="~/icon/Settings.svg" alt="" class="icon" />
                        <span class="description">Sign Out</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="main-content">
            <div id="menu-button">
                <input type="checkbox" id="menu-checkbox">
                <label for="menu-checkbox" id="menu-label">
                    <div id="hamburger"></div>
                </label>
            </div>
            <div class="main-body">
                <partial name="_Notification" />
                @RenderBody()
            </div>
        </div>
    </div>
    @*    <footer class="footer footer-center p-4 bg-base-300 text-base-content">
    <div>
    <p>Copyright © 2022 - Sistem Kasir - All right reserved</p>
    </div>
    </footer>*@
    @*    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - SistemKasir - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js"></script>*@
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemKasir/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}